//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingConsultation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingConsultation;

/**
 * Helper class for marshaling/unmarshaling ConsultationResponseSeq.
 **/
public final class ConsultationResponseSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, ConsultationResponse[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                ConsultationResponse.ice_write(ostr, v[i0]);
            }
        }
    }

    public static ConsultationResponse[] read(com.zeroc.Ice.InputStream istr)
    {
        final ConsultationResponse[] v;
        final int len0 = istr.readAndCheckSeqSize(10);
        v = new ConsultationResponse[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = ConsultationResponse.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ConsultationResponse[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, ConsultationResponse[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ConsultationResponseSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<ConsultationResponse[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            ConsultationResponse[] v;
            v = ConsultationResponseSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
