//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingConsultation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingConsultation;

public class ConsultationResponse implements java.lang.Cloneable,
                                             java.io.Serializable
{
    public String votingStation;

    public boolean isPrime;

    public long responseTime;

    public ConsultationResponse()
    {
        this.votingStation = "";
    }

    public ConsultationResponse(String votingStation, boolean isPrime, long responseTime)
    {
        this.votingStation = votingStation;
        this.isPrime = isPrime;
        this.responseTime = responseTime;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ConsultationResponse r = null;
        if(rhs instanceof ConsultationResponse)
        {
            r = (ConsultationResponse)rhs;
        }

        if(r != null)
        {
            if(this.votingStation != r.votingStation)
            {
                if(this.votingStation == null || r.votingStation == null || !this.votingStation.equals(r.votingStation))
                {
                    return false;
                }
            }
            if(this.isPrime != r.isPrime)
            {
                return false;
            }
            if(this.responseTime != r.responseTime)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotingConsultation::ConsultationResponse");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, votingStation);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isPrime);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, responseTime);
        return h_;
    }

    public ConsultationResponse clone()
    {
        ConsultationResponse c = null;
        try
        {
            c = (ConsultationResponse)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.votingStation);
        ostr.writeBool(this.isPrime);
        ostr.writeLong(this.responseTime);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.votingStation = istr.readString();
        this.isPrime = istr.readBool();
        this.responseTime = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ConsultationResponse v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ConsultationResponse ice_read(com.zeroc.Ice.InputStream istr)
    {
        ConsultationResponse v = new ConsultationResponse();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ConsultationResponse> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ConsultationResponse v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ConsultationResponse> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ConsultationResponse.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ConsultationResponse _nullMarshalValue = new ConsultationResponse();

    /** @hidden */
    public static final long serialVersionUID = 1294099930L;
}
