//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingConsultation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingConsultation;

public class SystemException extends com.zeroc.Ice.UserException
{
    public SystemException()
    {
        this.reason = "";
    }

    public SystemException(Throwable cause)
    {
        super(cause);
        this.reason = "";
    }

    public SystemException(String reason)
    {
        this.reason = reason;
    }

    public SystemException(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::VotingConsultation::SystemException";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::VotingConsultation::SystemException", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 801546518L;
}
